Repository codeit-bootcamp-nodejs/4-sprint-mission, pull requests merged in 2025-07, with the labels that each got.

#35 [김지헌] sprint2
  .gitignore
  README.md
  main.js
  models/Article.js
  models/Product.js
  package-lock.json
  package.json
  services/ArticleService.js
  services/ProductService.js
Labels: 매운맛🔥

#30 [이봉준] 스프린트 미션2
  .github/PULL_REQUEST_TEMPLATE.md
  src/Article.js
  src/ArticleService.js
  src/Product.js
  src/ProductService.js
  src/main.js
Labels: 매운맛🔥

#25 [신경렬] sprint 4 mission 2
  mission2/.gitignore
  mission2/Prettier
  mission2/README.md
  mission2/eslint.config.js
  mission2/package-lock.json
  mission2/package.json
  mission2/src/Article.js
  mission2/src/ArticleService.js
  mission2/src/Product.js
  mission2/src/ProductService.js
  mission2/src/README.md
  mission2/src/main.js
Labels: 순한맛🐑

#24 [이상욱]sprint2
  .gitignore
  README.md
  main.js
  main.js.backup
  main1.js.backup
  package-lock.json
  package.json
  services/ArticleService.js
  services/ProductService.js
Labels: 순한맛🐑

#34 [김태회] 스프린트 미션2
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Article.js
  ArticleService.js
  Product.js
  ProductService.js
  main.js
  package.json
Labels: 매운맛🔥

#27 [엄규리] sprint2
  .gitignore
  ArticleService.js
  ProductService.js
  README.md
  main.js
  package.json
Labels: 순한맛🐑

#50 [양정민] sprint2
  part1/Article.js
  part1/ArticleService.js
  part1/Product.js
  part1/ProductService.js
  part1/README.md
  part1/main.js
  part1/package.json
Labels: 미완성🛠️, 지각제출⏰

#40 [이서진] sprint2
  sprint_2/Article.js
  sprint_2/ArticleService.js
  sprint_2/Product.js
  sprint_2/ProductService.js
  sprint_2/main.js
  sprint_2/package.json
Labels: 순한맛🐑

#38 [조재후] sprint2
  .gitignore
  class/Article.js
  class/Content.js
  class/ElectroProducts.js
  class/Product.js
  main.js
  package.json
  services/.gitignore
  services/ArticleService.js
  services/ProductService.js
  services/axiosInstance.js
Labels: 순한맛🐑

#21 [송창준] Sprint Mission 2
  README.md
  article.js
  class.js
  product.js
Labels: 매운맛🔥

#20 [이하영] sprint mission2
  .github/PULL_REQUEST_TEMPLATE.md
  ArticleService.js
  ProductService.js
  class .js
  main.js
  package.json
Labels: 순한맛🐑

#5 [오연진] sprint1
  .gitignore
  README.md
  classes/Article.js
  classes/ElectronicProduct.js
  classes/Product.js
  main.js
  package-lock.json
  package.json
  services/ArticleService.js
  services/ProductService.js
  stores/ProductStore.js
  tests/testArticleService.js
  tests/testProductService.js
Labels: 매운맛🔥

#15 [김동현] sprint2
  README.md
  mission-2/Article.js
  mission-2/ArticleService.js
  mission-2/ElectronicProduct.js
  mission-2/Product.js
  mission-2/ProductService.js
  mission-2/main.js
Labels: 매운맛🔥
