Repository codeit-bootcamp-nodejs/4-sprint-mission, pull requests merged in 2025-08, with the labels that each got.

#79 [김태회] Sprint_mission_3
  .gitignore
  README.md
  sprint_mission_2/.github/PULL_REQUEST_TEMPLATE.md
  sprint_mission_2/.gitignore
  sprint_mission_2/Article.js
  sprint_mission_2/ArticleService.js
  sprint_mission_2/Product.js
  sprint_mission_2/ProductService.js
  sprint_mission_2/main.js
  sprint_mission_2/package.json
  sprint_mission_3/.gitignore
  sprint_mission_3/.prettierrc
  sprint_mission_3/.render-build.sh
  sprint_mission_3/eslint.config.mts
  sprint_mission_3/main.js
  sprint_mission_3/package-lock.json
  sprint_mission_3/package.json
  sprint_mission_3/prisma/migrations/20250805024154_init/migration.sql
  sprint_mission_3/prisma/migrations/migration_lock.toml
  sprint_mission_3/prisma/schema.prisma
  sprint_mission_3/prisma/seed.js
  sprint_mission_3/src/app.js
  sprint_mission_3/src/controllers/article_controller.js
  sprint_mission_3/src/controllers/comment_controller.js
  sprint_mission_3/src/controllers/product_controller.js
  sprint_mission_3/src/controllers/upload_controller.js
  sprint_mission_3/src/middlewares/errorHandler.js
  sprint_mission_3/src/middlewares/multer.js
  sprint_mission_3/src/middlewares/validation.js
  sprint_mission_3/src/prisma/client.js
  sprint_mission_3/src/routes/article_routes.js
  sprint_mission_3/src/routes/comment_routes.js
  sprint_mission_3/src/routes/product_routes.js
  sprint_mission_3/src/routes/upload_routes.js
Labels: 매운맛🔥

#71 [길도현] sprint 3
  sprint-mission-2/main.js
  sprint-mission-2/package.json
  sprint-mission-2/src/ArticleService.js
  sprint-mission-2/src/ProductService.js
  sprint-mission-3/.gitignore
  sprint-mission-3/README.md
  sprint-mission-3/app.js
  sprint-mission-3/middlewares/errorHandler.js
  sprint-mission-3/middlewares/multer.js
  sprint-mission-3/package-lock.json
  sprint-mission-3/package.json
  sprint-mission-3/prisma/migrations/20250801022001_init/migration.sql
  sprint-mission-3/prisma/migrations/20250801041126_init2/migration.sql
  sprint-mission-3/prisma/migrations/20250804002630_on_delte_add/migration.sql
  sprint-mission-3/prisma/migrations/migration_lock.toml
  sprint-mission-3/prisma/schema.prisma
  sprint-mission-3/prisma/seed.js
  sprint-mission-3/routes/article.js
  sprint-mission-3/routes/product.js
  sprint-mission-3/schemas/article.js
  sprint-mission-3/schemas/comment.js
  sprint-mission-3/schemas/product.js
  study/codeit-express/main2.js
  study/codeit-express/temp/main.js
  study/express-test/hello-world.js
  study/test.js
  study/test/src/utils/constants.js
Labels: 매운맛🔥

#92 [전범주] Sprint3
  .gitignore
  mission_2/README.md
  mission_2/main.js
  mission_2/package-lock.json
  mission_2/package.json
  mission_2/services/ArticleService.js
  mission_2/services/ProductService.js
  mission_3/.gitignore
  mission_3/main.js
  mission_3/package-lock.json
  mission_3/package.json
  mission_3/prisma/migrations/20250801011159_init/migration.sql
  mission_3/prisma/migrations/20250801073244_new_model_article/migration.sql
  mission_3/prisma/migrations/20250804063045_add_model_comment/migration.sql
  mission_3/prisma/migrations/20250807082719_on_delete/migration.sql
  mission_3/prisma/migrations/migration_lock.toml
  mission_3/prisma/schema.prisma
  mission_3/prisma/seed.js
  mission_3/routes/articles.js
  mission_3/routes/handler/errorHandler.js
  mission_3/routes/images.js
  mission_3/routes/products.js
Labels: 매운맛🔥

#75 [송창준] sprintMission3
  sprintMission2/article.js
  sprintMission2/class.js
  sprintMission2/product.js
  sprintMission3/controller/articleCommentLikeController.js
  sprintMission3/controller/postController.js
  sprintMission3/controller/productCommentLike.controller.js
  sprintMission3/middlewares/auth.js
  sprintMission3/middlewares/errorHandler.js
  sprintMission3/middlewares/uploads.js
  sprintMission3/middlewares/validate.js
  sprintMission3/package-lock.json
  sprintMission3/package.json
  sprintMission3/prisma/migrations/20250805062059_init/migration.sql
  sprintMission3/prisma/migrations/20250805092352_create_article/migration.sql
  sprintMission3/prisma/migrations/20250806001439_add_article_comment/migration.sql
  sprintMission3/prisma/migrations/20250806013858_add_product_comment/migration.sql
  sprintMission3/prisma/migrations/20250806052814_make_user_optional/migration.sql
  sprintMission3/prisma/migrations/20250806062902_add_comment_likes/migration.sql
  sprintMission3/prisma/migrations/20250807012938_fix_comment_like/migration.sql
  sprintMission3/prisma/migrations/migration_lock.toml
  sprintMission3/prisma/prismaClient.js
  sprintMission3/prisma/schema.prisma
  sprintMission3/prisma/seed.js
  sprintMission3/routes/article.routes.js
  sprintMission3/routes/articleComment.routes.js
  sprintMission3/routes/articleCommentLike.routes.js
  sprintMission3/routes/commentLike.routes.js
  sprintMission3/routes/postRoutes.js
  sprintMission3/routes/product.routes.js
  sprintMission3/routes/productComment.routes.js
  sprintMission3/routes/productCommentLike.routes.js
  sprintMission3/server.js
Labels: 매운맛🔥

#93 [조재후] Sprint 3
  sprint2/.github/PULL_REQUEST_TEMPLATE.md
  sprint2/.gitignore
  sprint2/class/Article.js
  sprint2/class/Content.js
  sprint2/class/ElectroProducts.js
  sprint2/class/Product.js
  sprint2/main.js
  sprint2/package.json
  sprint2/services/.gitignore
  sprint2/services/ArticleService.js
  sprint2/services/ProductService.js
  sprint2/services/axiosInstance.js
  sprint3/.gitignore
  sprint3/.prettierrc
  sprint3/README.md
  sprint3/http/articles.http
  sprint3/http/products.http
  sprint3/package-lock.json
  sprint3/package.json
  sprint3/prisma/migrations/20250814171309_init/migration.sql
  sprint3/prisma/migrations/migration_lock.toml
  sprint3/prisma/schema.prisma
  sprint3/src/app.js
  sprint3/src/client/prismaClient.js
  sprint3/src/routers/articleRouter.js
  sprint3/src/routers/commentRouter.js
  sprint3/src/routers/productRouter.js
Labels: 미완성🛠️, 순한맛🐑, 지각제출⏰

#78 [이재훈] sprint3
  .gitignore
  package-lock.json
  package.json
  sprint/ApiService/ArticleService.js
  sprint/ApiService/ProductService.js
  sprint/README.md
  sprint/main.js
  sprint3/app.js
  sprint3/backup.sql
  sprint3/middlewares/errorHandler.js
  sprint3/middlewares/validate.js
  sprint3/prisma/migrations/20250805082005_sprint3/migration.sql
  sprint3/prisma/schema.prisma
  sprint3/prisma/seed.js
  sprint3/routes/articleComments.js
  sprint3/routes/articles.js
  sprint3/routes/image.js
  sprint3/routes/productComments.js
  sprint3/routes/products.js
Labels: 매운맛🔥

#88 [이제창] sprintMission3
  .gitignore
  index.js
  middlewares/validation.middleware.js
  package-lock.json
  package.json
  prisma/index.js
  prisma/migrations/20250817033539_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
  routes/articles.router.js
  routes/products.router.js
  routes/upload.router.js
Labels: 순한맛🐑
